### PR TITLE
Replace Use of Deprecated APIs

### PR DESCRIPTION
**Pull request by celluj34**
Hi @manuth ! No word yet on https://github.com/dsherret/ts-nameof/pull/123 so I thought I'd make this same PR in your fork.

Do you have an npm-published version of this code? I'd like to give it a try so I can upgrade to TS5.

### CODE REVIEW

**Comment by celluj34** [comment]
Okay, sounds good, thanks!

**Comment by manuth** [comment]
No problem - I'll let you know once I finished refactoring this.
There are a few things I'd like to take care of before releasing.

Let me know if there is something you'd add to the list:
* Remove unnecessary packages from mono repo
* Report errors to `ttypescript` or `ts-patch`ed TypeScript respectively
* Replace `@types/ts-nameof` with package hosted outside of `DefinitelyTyped` (I have the package name `@typescript-nameof/types` in mind)

**Comment by celluj34** [comment]
* Removing unnecessary packages is always great but I'd say for now if it works, don't mess with it too much
* I don't use `ttypescript` or `ts-patched` so those aren't super important to me
* If we could get types included by default that would be even better, IMO. I understand that means people who use javascript only would be downloading useless typescript information, but that's a tradeoff I'm willing to make ;)

**Comment by manuth** [comment]
Get you on that one - however, types _need_ to be in a `@types/`-package in order to get picked up by the TypeScript compiler without having to import the module containing the type declarations.

This is - at least when using `ttypescript` or `ts-patch` - the behavior you'd want when using `ts-nameof`.

How are you using `ts-nameof`?
Using babel?

**Comment by celluj34** [comment]
Okay, makes sense. I've never written or published any sort of npm package so I don't know what all goes into making it work.

I'm not using babel, just typescript + webpack into javascript.

**Comment by manuth** [comment]
Hello @celluj34 
Thanks I thought it might make sense to inform you that this project is finally released.

Feel free to head to the `README.md` file to find out how to set it up.

**Pull request closed without merging**
